version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - network1
      
  abernathyNote:
    depends_on:
      - mongodb
    image: abernathy-notes
    container_name: abernathy-note
    restart: always
    ports:
      - "8081:8081"
    build:
      context: ""
volumes:
   mongodata:

networks:
   network1: